#!/bin/bash

set -e

error() {
    echo "$1" >&2
    exit 1
}

usage() {
    echo "Usage: `basename $0` -n <NAME> -i <IMAGE> [-r <RUN-ARGS>] [-x <X-NUM>] [-s <y|n>] [MOUNT]..." >&2
    exit 1
}

RUN_ARGS=""
X_FILE=""
MOUNTS=""
PORTS=""
SOUND="n"

while getopts ":n:i:r:x:s:m:p:" o; do
    case "$o" in
    n)
        NAME="$OPTARG";;
    i)
        IMAGE="$OPTARG";;
    r)
        RUN_ARGS="$OPTARG";;
    x)
        (( OPTARG >= 100 )) || error "Bad X number."
        X_FILE="/tmp/.X11-unix/X$OPTARG"
        [[ -e "$X_FILE" ]] || error "Bad X number."
        ;;
    s)
        SOUND="$OPTARG";;
    m)
        MOUNTS="$OPTARG";;
    p)
        PORTS="$OPTARG";;
    *)
        usage;;
    esac
done
[[ -z "$NAME" ]] && error "No name specified."
[[ -z "$IMAGE" ]] && error "No image specified."

declare -a DOCKER_ARGS
for mount in $MOUNTS; do
    [[ "$mount" =~ ^(/media/hdd/downloads|/home/kagome/[-A-Za-z0-9]+/[-A-Za-z0-9/]+):/[-A-Za-z0-9/.]*(:ro)?$ ]] || error "Bad mount."
    DOCKER_ARGS+=("-v $mount")
done
for port in $PORTS; do
    [[ "$port" =~ ^[0-9]+:[0-9]+$ ]] || error "Bad port."
    DOCKER_ARGS+=("-p 172.17.42.1:$port")
done
[[ "$X_FILE" ]] && DOCKER_ARGS+=("-v $X_FILE:/tmp/.X11-unix/X0")
if [[ "$SOUND" == "y" ]]; then
    # XXX: Bash can't export declare -a array to subshell so create one big arg.
    cd /tmp  # Forkaround for find
    DOCKER_ARGS+=( $(find /dev/snd -type c -exec echo '--device {}:{}' \;) )
fi

exec docker run --name "$NAME" -i -t --rm ${DOCKER_ARGS[@]} "$IMAGE" $RUN_ARGS
